# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: soccer 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "soccer"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["savroff", "svyatmuzyka"]
  s.date = "2015-09-28"
  s.description = "Soccer manager engine with match generator."
  s.email = "savroff@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/soccer.rb",
    "soccer.gemspec",
    "test/helper.rb",
    "test/test_soccer.rb"
  ]
  s.homepage = "http://github.com/savroff/soccer"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Soccer manager game engine."

  # Don't support old Gem::Version
  s.add_runtime_dependency(%q<puma>, [">= 2.14.0"])
  s.add_runtime_dependency(%q<sequel>, [">= 0"])

  s.add_development_dependency(%q<shoulda>, [">= 0"])
  s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
  s.add_development_dependency(%q<bundler>, ["~> 1.0"])
  s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
  s.add_development_dependency(%q<simplecov>, [">= 0"])
end

